{% set name = "casa_formats_io" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 169423d17799eefbcecd433ffb9a86e85470357977833a14048b58750d4ce26e

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy {{ numpy }}  # [py<39]
    - numpy >=2.0.0  # [py>=39]
    - setuptools
    - setuptools_scm
  run:
    - python
    - astropy >=4.0
    - numpy >=1.21
    - dask >=2.0

test:
  imports:
    - casa_formats_io
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs casa_formats_io.tests

about:
  home: http://casa-formats-io.readthedocs.org
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Dask-based reader for CASA data
  description: A small package implementing I/O for CASA data formats
  doc_url: http://casa-formats-io.readthedocs.org
  dev_url: https://github.com/radio-astro-tools/casa-formats-io

extra:
  recipe-maintainers:
    - keflavich
    - mwcraig
    - astrofrog
